# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b997aedda802b82e808d3ec5f5ce36cb0fe417a11cf3794b77bdbd9ce8ce7e5a03d87a558dd172aafc08c8f971cfbfbad1bf94f9c687e8db0c5235d99ebc01

test:
  secret_key_base: fe90e344e05b068fecb45b2d57e970edae20438584f01a51e3b5751b5a0b94c7c4c710d7e2abfdb55339e63fb110d603e27ef11313cd9377975998d8d45f2aac
  devise_secret_key: 23ca5781569398fc3a7866abbc49ac6cedf4d039939b480940635530c78504dbb7140bf61ac26055b7629daaaf197ba308e491a189588d36e95f2c7da066347b
  redis_url: 'redis://localhost:6379'
  ab_redis_url: 'redis://localhost:6379'
  secret_key_base: f1e87ee0a63eac59449c0b764a7975b3e7866b2f50ca91f30190d20845dd13d48e2a7f4ce84c31409c330fcf04ba4921bf1c3a9a3973395750f8d526acdf250d
  stripe_secret_key: sk_test_Vsbyrd3B5wTpmQ1AV1lVqLio
  stripe_publishable_key: pk_test_0msy2mtV9u9bVjjPECOYsS4w
  sailthru_api_key: 17e45774c18d1db8b8692db9a336db0c
  sailthru_api_secret: 9b76b6070135a7a03363c744f6e9e046
  tax_cloud_api_id: 9F45ED0
  tax_cloud_api_key: BCB97975-E6C0-40AE-8879-C12AEA173DF6
  google_analytics_id: UA-57467612-2
  aws_access_key: AKIAJPREMLX5WZNAL4EQ
  aws_secret_access_key: 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
  aws_region: us-east-1
  travisci_access_token: ''
  datadog_api_key: ''
  fosdick_ftp_host: ftp.fosdickcorp.com
  fosdick_ftp_user: primaryk
  fosdick_ftp_password: pk111814
  bluecore_ftp_host: triggermail.exavault.com
  bluecore_ftp_user: primary
  bluecore_ftp_password: n1bZrQq18p
  fastly_api_key: testkey
  zendesk_user: zendesk-api@primary.com
  zendesk_password: Bi9a6v^%Dt4N^6eW7=,v
  mixpanel_token: <%= ENV["MIXPANEL_TOKEN"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
